# Generated by Django 3.2.3 on 2021-05-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gesture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('moveX', models.TextField(default='', null=True)),
                ('moveY', models.TextField(default='', null=True)),
            ],
        ),
    ]
