# Generated by Django 3.2.3 on 2021-05-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soowa_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gesture',
            name='moveX',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gesture',
            name='moveY',
            field=models.TextField(),
        ),
    ]
