# Generated by Django 3.2.3 on 2021-05-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soowa_web', '0003_auto_20210521_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='gesture',
            name='gestureNum',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
