# Generated by Django 3.2.3 on 2021-06-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soowa_web', '0005_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
